mysql:
  host: mysql20.mydevil.net
  port: 3306
  database: m1148_hackyeah18
  username: m1148_hackyeah18
  password: 1598264Hackyeah18

google:
  secretkey:
  api:
    url: https://maps.googleapis.com/maps/api/directions/json